### ISSUE TITLE
Case when (solar_voltage < battery_voltage + solar_voltage_offset_stop)

### ISSUE THREAD

**Issue by fhlb-tech** [LibreSolar/MPPT-Charger_Software#5]
I'm a bit confused on how will the solar panel behave when the voltage starts to drop and reach the minimum input voltage of the DC/DC converter. The charging process will stop, then the current will drop and the voltage of the solar panel will rise again. 
You placed a 4V hysteresis to prevent charging continuous recycles. ( difference between "solar_voltage_offset_start" and  "solar_voltage_offset_stop")
Can we actually change the cutoff behavior and try to squeeze more power from the panels by trying to reduce the charging current (if possible) until charging current is smaller than the minimum?

another question that's lurking in the back of my mind is: I'm new to this solar panels thing and never tested or worked with any. I'm curious to know what will I lose if I use those 40V max open voltage panels to charge a 12V li-ion battery pack. A buck converter that will shutdown the charging voltage at 12.6+5=17.6V seems an awful decision compared to a buck-boost converter (specifically I'm also studying microchips AN1521 circuit).
I want to ask you, in your opinion, will I face this condition very often? Do you think I'll regret using this circuit over a buck boost converter?
Huge respect mate... your work is more precious than gold

**Comment by martinjaeger** [comment]
In the current version of the software, I also added a dcdc restart interval of 60s (in addition to the voltage hysteresis). You are completely right. With only the voltage hysteresis, the MPPT might toggle between on and off for some minutes during dusk because the open circuit potential of the PV panel is still too high.
The charging current is measured at the output. When it reaches the minimum cut-off limit, this was already the maximum you can get, as the input is still in the maximum power point.

For a 12V system with 40V panel, the additional yield if the solar voltage can go below the battery voltage (buck-boost converter) is negligible. It's already almost dark under these conditions.

The software is currently under heavy rework in order to integrate the CAN communication. I hope to clean up and upload a new version soon.
